apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: moltbook-db-credentials
  namespace: moltbook
spec:
  encryptedData:
    password: AgBBKD/eom0/6mHR32UFcMj4SUR48Gtg5MksTcWBwsgRs0G/l92asIxSWtpKXsZ5XPrGUiCDB3SCzMYRV6YK7hcz0oPVcW/BaneyLTrgLMvdjc97F9rn73v+UOZj2wgDReRe+frheMYfUfzRfDtn3sGladGBZwyXqEG5p3FpZ4oe0tsqnLihmxTImyUChapyHpsEHMZXJjx9JTIWPst1Qm2mcevK+Hv61VjDsJaBaztk4lGhLj1M8QrvdIVUfEni0d0TuDiO/Dr70z4sIX7U0kiM5BwcDGrmuqqx6Bi1fYSIZS/tE4QU//fNNUZyNgmzh5GqoV1XLns5eYEkd7eopUnS5YR7ICdPl94ikNPjWPpswz3x1cae2rwggx7a1QN8N6xR/d9FQ8s7MgqiMjIXNY9StTwaaqJ0h+SGLOm74pXB4bDAeE4Yekd1ARil9aXqxRRSniwXa7HQoicCOnPBY3SiUo7xMLPLr2NeA12iRaKmW+R/NZWtjgH2se6FWV1NaP3j/UUxTQOO+XXMT0018zgyhYGY70L/QcGqDx/vvmlXD5Ug74dJruBbalAX9K5/QsUBJ6qSbQPkFlD1tFubB2aKNLFQFPFuk6mkAvk2AwbtUpywWZIWH0P2wxlTtOhscAnY6AgOspi/WgowZhBvpNgH9DPtM/HGByD9sIYFzdaHzAYL4Ykdcxu2SQu+DF5un5im9Mb2A9Phyd8OFtvFYaRYCOQcT9jd77xbmuhQ2TyNtA==
    username: AgBXmcVrRwAdSd3qH6qTJRNlZRNLKDLZ4By//gzrkZakxmzNhHEnCRD6Xk8or+wHbzULa/cK2QFWEo9l1f8q1OeJzoGmZ6h4W5rpRo5Zjk2wkNEc5nyfc3cR6brCrONuAfQKyAOIbXsHsHSKPuqSa/WW/YXsfBYo8+zgfqsMBFoMztt2YlkRA5g/1lXn9INWlwxNdauf2mjq4t4YJG/jlRMgcqbYMGfCcsd3WUlKfuSB//Tx20jJG93qnyho0N8Jq2fSrNZLdQRiJGm6xcSSLiRnMwjevfcbXAJDyJmZG4Rq27DObJkRYApRbzFofzmj1MsrTdD7WpOmfXYunpNsjqoPsm+d4/z2BTGrOyJmiTcJdA8LQbTFG8JFvKNcg8QrRSkNDyk2u7PeXXPDuPV0/qC7Rwo5Wz4ZU2LaI5kQCv6wlAb6chYR9E2NsAX0isUVDFdnOZoRd66PXgjtI0jZOuDd12c6oSeGbnxD8WDi+TVizNYLonzA5TCdo0iCpJotYRWMz61K74V570S/Bq+CvA18gpStbYQ39mQTlDHbhGVZVh5CL7mYVnklPINLC+g9ON6737+eUpSgtdN/nZpWT+ba2kWNZZgu5K0Nmam5ZMUXH15tNa+iebgfebznTCJxdspSFAK3bC9faHQY2z25xc8nDGoXbW3TwTIr7A8reHQfXdvoUKjG80AU7A+UWm0eyoKa9X+yp2OSZw==
  template:
    metadata:
      creationTimestamp: null
      name: moltbook-db-credentials
      namespace: moltbook
    type: Opaque
---
