apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: moltbook-postgres-superuser
  namespace: moltbook
spec:
  encryptedData:
    password: AgBStuPjVzD9XxUHFXYz/vm49vD21p+DdMhJcW0qbfTRylf7rDvo3yIgHU1WJm5YRJ/D5P8c851uL1ODnU5z4R3kUlUrG/vunjobYxvDDbsCBaeH+e54MzKfiRWRrRTijkIbKtxb2VWHIpR8Z7EgJPGDMbzbFfTSJ+0g4PlBwD2Dimsqo/mXWXs8G72voUdHri0pEg+LLbLIxkh0ci3xXy6Ef3lRwrogjCyJT6oHVFVKDoDcrmjjds+RyeuRm4BIPXw2Qe2y1IbcIPTTM0GXaEW2sJyZQFfIJWjB/fVU8qqxmnG60Lp7vFPUVrAJqvsTflJ3vx9IyYIe9NmtOwkx4VZjv886tQHwCrnjrkWV5adIE4HWd3CG5hXUFcn92tBKlPGH9jwv+2H5/fylPqTlWvaC3Urx6Ex1/GiO7hOPBYmjtW9o3kovrTqmYGh3AuoTMOXu28UlkWLOMCq3XUj7O+1YgNBQVdWCRP6bA1yD+m4n09yShiGxp5gAoPnC2iXxRPfoRmC8Sa+a+4zQUXazsMrbWuSz5Mvc9R8P1aI0sDskMZPHpEOS6/Us1qQ6vWZWluZ8275ApT1XAeemZWQ63azc9XMyfFHpWC3Wqw22x3P4AoUpJaCRrrVGvqVUovkxLoOi/VoywRBuVOXmkXHAMP+mYALF5YYRrmFiqEXp6SixFSxRoy0Rb1hbkyOCPYwrritPsk1Z7aKcUVRvWSGjef/WzJ9o7vdMrNWT55gEkRsZ1w==
    username: AgAVInpjMcYUspgLEtZvuyELT6aeYyxnctyhFgV/Spqy93fuYmaEmWCXM4XBp0Xs9Rr0RnVd4mcFdFcqpMql0Grc8Tli/nPNQ8l34PWOW24nc32v/oN/44+Wpyi7loWbQQkGCxeMY9gsQPVZZfgDH7WH6VdhPbdGagtiMfzw+x/c2xcDosd2+fi9oMtrYtocYd3NIfbW6O8z2WIDPSPDd6WOBSdRDDyL+w9cf0KSbRMj/+lTOdLmKCNvChwrowSBs5FFcFcVUmv4Z2H9TWDbB1XSHgD1ae3P0p+JrvJJcfODNf20nqhWBioZHlj+lh87Qrj16GK6Ct/Btxowk2eIQ7g/XYxyu8IeFW1pZCx1cl5e8oJzzQbYo5WDmULSjAHeH4whp7pbvs5fd+PNYfLYzfrDtAlqwek47vM+fuIo2+nIyXeOVb+JwEr5Pq38UJifcol46iNmQaq67iNa8fySqfOe8pqBOkWYKrnPrd6hLiw+9y8O1TbglyihDB+IJaLYSsNDGod17J7fuHENx8jlWwcSxPJt9wjDMBWvOV9jWXYdBrTQIE7J5rBOG8Cmhuxfh7tRxOlC2nwHYLG3TDZE3qjT+wZZEOmRegbLsYjaqG0/IdQzf+PEafwx8ND+pBk9JX6jq+Utx+pO3iR6kN1kvkoz8WI1B/TS9Th4KfphpMbQOFCofFmMHAAyBiE+a5bw/hnOroH7s7nIsA==
  template:
    metadata:
      creationTimestamp: null
      name: moltbook-postgres-superuser
      namespace: moltbook
    type: kubernetes.io/basic-auth
---
