apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: moltbook-postgres-superuser
  namespace: moltbook
spec:
  encryptedData:
    password: AgAdplANjssm8yoRKlZbFSwiBrvkaBKJyDbvYH8bmKzqC7CWn8aXtqoUfsohLQc0hckdFRfwwnESaU89zd0xVP2k1G53n1OPsLqXQX2PP9AJDHA+1PzKKSyWe+TBwst7VGqn47qPnNGgkrRCqi28GKeVZVqzSNv7eb8W3EEg47TWB4eTMiz7zQ2pqvOYiY+UG7Kt3LsskcI9L0mpFWBUg+272Rhd8tul0UMvAzKAuTMsISCwmcFR9ZxRnsxVeJ6HFugnmzK5oP/BjEXWJ3UhreeZcgNSboBWNTr7SWSWeIc6V2PuS1IXEv/GpppzX5UftHld2MJZkTtTY+9Syken9opF4rLX3XEjPhCE7H3QorhEjxMUyoR5hzU4WpUORiFb9AUuZqx3kyDHkuF93Zx/8A5zOGps1Ltq3RsG76UIadABkpkg8qSPli/P3fvbaB5mOccU12FS+vHQYwA6WD8G3AvN0IBgfNlfQnQbMPBo/z5IA8oaay0Lurkr7nCQdNZM5o/JixNdPXYAaC3nIeJ0TmlyaUV5v6KkU8Mu3CaqUcRl3Pfmy/ODn1woz7/tssEEad3Q7lA8xqjnRmx9DBU9w6Bl+hIE9yOTxapXMub8JI85X+3JqkAx7y6ntxJffoYi4utNu3/2Jgl75kCKiX3PY+TUk0R2tQ+3D0jrKJtmn2pLiuYvDRjsf55+TBcisB33IM0HQrpnhFqmqARFw1gmCncZ7gBMdQJLWBxx4xp4Rqj4Sg==
    username: AgBOKW4OLERrjBr5wborsCBkAvjYaHNYVFqePvQHjg9uCqAJNSQcwPOz6J6HQtOMIJmPfep0zastayklftbyWN2N1WQV4cTHIYiouP4D2exvyiY0utTK0NJaWHGVlwIICQaIJqdGi1W20ruzdCH1Ik1pR5zXV1/dD3WWJKqIAhqXbAfkoZVOxsIQNGCEyM/VgFHowR83ExGYbDqOO5NaG0ZIljAxAMmZZUYX1adpUhrPsucKSnOq/KXDPYVBgmvLhJx19TQbFzUs5Tm83PDe+GSrMKZytxhX9EMslKNzuU6QZ/zKXnatExAOBAyXAVXYe8gN+jXVVuZGXzRSlaiYDrEgQRCteCaBWLBJjn9fgTgtyKPgC5pDD+AA+/GunP5J7vsfCI544wUkLD0z5VcTNngNIsTUc1zjIclR9pFFlIaQUSXuqBDVj3oqmzHTtALL1Av/7pqo9xdur1ZuK+V75gwy3TeyZIJyTmGluFaOuPsNI4nU5XG5njQBMqsJEOPgSkOXnYnUGp1q60HUuGfxf1P/Fg3xXSkpN3olp29eyWcBC2mNV6EatF2UagTcdr5p11w4efJTAtr+0kG1w4HYtCGJeRVgNe6bzDrZFlqzvMEWZNkk2OgG8zej8UctoHQrvs82gkoi/+3TYgrP9BqkH4a/zF7od5LEjqWCFmJCofaVvfP+PBRq6jQ3k63b5SQkPBbd4BOL5Wt0kg==
  template:
    metadata:
      creationTimestamp: null
      name: moltbook-postgres-superuser
      namespace: moltbook
    type: kubernetes.io/basic-auth
---
